---
pages:
- post/test.md
hide_body: false
is_partial: false
fields:
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: thumbnail
  label: Thumbnail
  type: text
  hidden: false
  default: ''
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: type
  label: Type
  type: text
  hidden: false
  default: ''
